---
pid: /home/rails/apps/freddy/thin.pid
log: /home/rails/apps/freddy/thin.log 
rackup: /home/rails/apps/freddy/config.ru
timeout: 30
port: 4666
max_conns: 10
max_persistent_conns: 512
environment: production
address: 127.0.0.1
servers: 1
daemonize: true